services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://65.21.254.61
      - VITE_DEV_SERVER_KEY=
      - VITE_DEV_SERVER_CERT=
    env_file:
      - .env.production
    depends_on:
      - mysql
    networks:
      - app-network
    restart: unless-stopped
    command: >
      bash -c "
        chown -R www-data:www-data storage bootstrap/cache database &&
        chmod -R 775 storage bootstrap/cache &&
        touch database/database.sqlite &&
        chmod 666 database/database.sqlite &&
        cd /var/www/html &&
        composer install --no-dev --optimize-autoloader &&
        npm install &&
        rm -f public/hot &&
        npm run build &&
        echo 'Waiting for MySQL to be ready...' &&
        until php -r \"try { new PDO('mysql:host=mysql;port=3306;dbname=${DB_DATABASE}', '${DB_USERNAME}', '${DB_PASSWORD}'); echo 'Connected!'; exit(0); } catch(Exception \$e) { exit(1); }\"; do
          echo 'MySQL not ready yet, waiting 5 seconds...'
          sleep 5
        done &&
        echo 'MySQL is ready!' &&
        php artisan config:cache &&
        php artisan route:cache &&
        php artisan view:cache &&
        echo 'Assets built and cached, starting Apache...' &&
        supervisord -c /var/www/html/supervisord.prod.conf
      "

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env.production
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
